export const GET_ORDER_INGREDIENTS_REQUEST = "GET_ORDER_INGREDIENTS_REQUEST";
export const GET_ORDER_INGREDIENTS_SUCCESS = "GET_ORDER_INGREDIENTS_SUCCESS";
export const GET_ORDER_INGREDIENTS_FAILED = "GET_ORDER_INGREDIENTS_FAILED";
