export const SET_STUFFING_INGREDIENT: "SET_STUFFING_INGREDIENT" = "SET_STUFFING_INGREDIENT";
export const DELETE_STUFFING_INGREDIENT: "DELETE_STUFFING_INGREDIENT" = "DELETE_STUFFING_INGREDIENT";
export const SET_BUN: "SET_BUN" = "SET_BUN";

export const REPLACE_WITH_SORTED_STUFFING: "REPLACE_WITH_SORTED_STUFFING" = "REPLACE_WITH_SORTED_STUFFING";
export const REMOVE_ALL_STUFFING: "REMOVE_ALL_STUFFING" = "REMOVE_ALL_STUFFING";
