export const SET_SELECTED_INGREDIENT = "SET_SELECTED_INGREDIENT";
export const DELETE_SELECTED_INGREDIENT = "DELETE_SELECTED_INGREDIENT";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const SET_MODAL_TYPE = "SET_MODAL_TYPE";
export const DELETE_MODAL_TYPE = "DELETE_MODAL_TYPE";
